### ISSUE TITLE
v1 Release checklist

### ISSUE THREAD

**Issue by arshbot** [arshbot/lnt#10]
v1.0.0 release checklist

- [ ] [speed up `lnt view channels` for the love of god](https://github.com/arshbot/lnt/issues/14)
- [x] [view peer](https://github.com/arshbot/lnt/issues/6)
- [ ] [view invoices](https://github.com/arshbot/lnt/issues/15)
- [ ] view invoices --summary
- [x] [kill channel](https://github.com/arshbot/lnt/issues/12)
- [ ] [kill zombie channels](https://github.com/arshbot/lnt/issues/13)
- [ ] [view channel by id](https://github.com/arshbot/lnt/issues/8) ( search across APIs ) for LND knowledge of chan
- [ ] [view invoices paid by last channel](https://github.com/arshbot/lnt/issues/18)
- [ ] [add column to view channel for payments made through channel ( not forwards )](https://github.com/arshbot/lnt/issues/16)
- [x] Migrate over to /arshbot/lnt
- [ ] [remove not implemented options](https://github.com/arshbot/lnt/issues/17)
